// Generated by CoffeeScript 1.7.1

/*
Copyright (c) <2014> Florian Mounier - paradoxxxzero

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 */
var Selection, display;

Selection = (function() {
  function Selection() {
    this.selection = null;
    this.begin = this._begin.bind(this);
    this.select = this._select.bind(this);
    this.end = this._end.bind(this);
    addEventListener('mousedown', this.begin);
  }

  Selection.prototype.style = function() {
    this.selection.style.position = 'fixed';
    this.selection.style.backgroundColor = 'rgba(0, 0, 255, 0.2)';
    return this.selection.style.border = '2px solid rgba(0, 0, 255, 0.8)';
  };

  Selection.prototype.position = function() {
    if (this.portion.w >= 0) {
      this.selection.style.left = "" + this.portion.x + "px";
      this.selection.style.width = "" + this.portion.w + "px";
    } else {
      this.selection.style.left = "" + (this.portion.x + this.portion.w) + "px";
      this.selection.style.width = "" + (-this.portion.w) + "px";
    }
    if (this.portion.h >= 0) {
      this.selection.style.top = "" + this.portion.y + "px";
      this.selection.style.height = "" + this.portion.h + "px";
    } else {
      this.selection.style.top = "" + (this.portion.y + this.portion.h) + "px";
      this.selection.style.height = "" + (-this.portion.h) + "px";
    }
    return this.selection.style.zIndex = 99999999;
  };

  Selection.prototype._begin = function(e) {
    document.body.style.webkitUserSelect = 'none';
    removeEventListener('mousedown', this.begin);
    this.portion = {
      x: e.clientX,
      y: e.clientY,
      w: 0,
      h: 0
    };
    this.selection = document.createElement('div');
    this.style();
    this.position();
    document.body.appendChild(this.selection);
    addEventListener('mousemove', this.select);
    return addEventListener('mouseup', this.end);
  };

  Selection.prototype._select = function(e) {
    var x, y;
    x = e.clientX;
    y = e.clientY;
    this.portion.w = x - this.portion.x;
    this.portion.h = y - this.portion.y;
    return this.position();
  };

  Selection.prototype._end = function() {
    removeEventListener('mousemove', this.select);
    removeEventListener('mouseup', this.end);
    document.body.removeChild(this.selection);
    if (this.portion.w < 0) {
      this.portion.x += this.portion.w;
      this.portion.w *= -1;
    }
    if (this.portion.h < 0) {
      this.portion.y += this.portion.h;
      this.portion.h *= -1;
    }
    this.done(this.portion);
    return document.body.style.removeProperty('-webkit-user-select');
  };

  return Selection;

})();

display = function(imagedata) {
  this.overlay = document.createElement('div');
  this.overlay.style.position = 'fixed';
  this.overlay.style.top = 0;
  this.overlay.style.left = 0;
  this.overlay.style.width = '100%';
  this.overlay.style.height = '100%';
  this.overlay.style.display = 'flex';
  this.overlay.style.justifyContent = 'center';
  this.overlay.style.backgroundColor = 'rgba(0, 0, 0, 0.2)';
  this.overlay.style.zIndex = 999999;
  this.img = document.createElement('img');
  this.img.style.alignSelf = 'center';
  this.img.style.maxWidth = '50%';
  this.img.style.maxHeight = '50%';
  this.img.src = imagedata;
  this.overlay.appendChild(this.img);
  document.body.appendChild(this.overlay);
  return this.overlay.addEventListener('click', (function(_this) {
    return function(e) {
      if (e.target === _this.overlay) {
        return document.body.removeChild(_this.overlay);
      }
    };
  })(this));
};

chrome.extension.onMessage.addListener(function(message, sender) {
  var sel;
  switch (message.cmd) {
    case 'select':
      sel = new Selection();
      return sel.done = function(selection) {
        return chrome.extension.sendMessage(sender.id, {
          cmd: 'capture',
          data: selection
        });
      };
    case 'image':
      return display(message.data);
  }
});
